/**
 * "Now playing" annotation for a matchday room: which fixture the current round's content actually
 * came from. Before gameday mode, a room only ever had one fixture for its whole lifetime, so nothing
 * needed to say so explicitly — gameday mode rotates rounds across several, so a guest/host mid-game
 * otherwise has no way to tell (M1/M2/M3's own public payloads carry player/market data, not the
 * fixture identity).
 *
 * Deliberately API-layer-only bookkeeping: it never touches `ProjectedRoom` (a pure `game-core` type)
 * and never re-derives anything from a live provider call — it only reads whatever `data-context.ts`
 * already cached for this room. `dispatch.ts`'s `project()` attaches the result as a sibling field on
 * the broadcast payload, alongside the engine's own projection.
 */

import type { Fixture } from '@fdg/football-data';
import type { RoomId, RoomState } from '@fdg/game-core';
import { activeSession } from '@fdg/game-core';
import { getCachedGameday, getPinnedRoundFixture } from './gameday-cache.js';
import { getCachedBundle } from './matchday-cache.js';
import type { RoomMeta } from '../rooms/store.js';
import { isRotationRoom } from '../rooms/store.js';

export interface CurrentFixtureSummary {
  readonly fixtureId: string;
  readonly competitionId: string;
  /** `'single'` for the original one-fixture-per-room flow, `'gameday'` when this round was picked
   * by rotation across a competition's live fixtures. */
  readonly mode: 'single' | 'gameday';
  readonly homeTeam: { readonly name: string; readonly crestUrl: string | null };
  readonly awayTeam: { readonly name: string; readonly crestUrl: string | null };
}

const toSummary = (fixture: Fixture, mode: CurrentFixtureSummary['mode']): CurrentFixtureSummary => ({
  fixtureId: fixture.id,
  competitionId: fixture.competitionId,
  mode,
  homeTeam: { name: fixture.homeTeam.name, crestUrl: fixture.homeTeam.crestUrl },
  awayTeam: { name: fixture.awayTeam.name, crestUrl: fixture.awayTeam.crestUrl },
});

/** `null` for a general room, or a matchday room whose data has not been prefetched yet (e.g. still
 * on the loading screen). Synchronous and cache-only — never awaits or calls out to a provider. */
export const resolveCurrentFixtureAnnotation = (
  roomId: RoomId,
  room: RoomState,
  meta: RoomMeta,
): CurrentFixtureSummary | null => {
  // Gameday rooms and explicit multi-fixture pools share the rotation/pinning machinery.
  if (isRotationRoom(meta)) {
    const entry = getCachedGameday(roomId);
    if (entry === null) return null;

    // The *last generated* round in the active session — `(activeSessionIndex, rounds.length - 1)`,
    // mirroring `readActiveSlice` in `reducer.ts` exactly, and the same identity
    // `resolveNextRoundKey` in `data-context.ts` would have used to pin this round's fixture when it
    // was generated. Stays correct after the session has since advanced to `intermission`/finished:
    // `activeSessionIndex` only ever changes on the next `START_SESSION`, never underneath a session
    // that is merely done producing rounds, so a round's key never shifts out from under it.
    const sessionIndex = room.activeSessionIndex;
    const session = activeSession(room);
    if (sessionIndex === null || session === undefined || session.rounds.length === 0) return null;
    const roundIndex = session.rounds.length - 1;

    // Resolve a round that has already been generated by its pin FIRST, independent of
    // `fixtureOrder` (rotation *eligibility*, which legitimately shrinks as fixtures stop being live).
    // `bundle.fixtures` is grow-only — never pruned — precisely so an already-happened round's
    // fixture identity keeps resolving here even after every fixture has since left the live set.
    const pinnedFixtureId = getPinnedRoundFixture(roomId, { sessionIndex, roundIndex });
    if (pinnedFixtureId !== null) {
      const bundle = entry.bundle.fixtures.find((candidate) => candidate.fixture.id === pinnedFixtureId);
      return bundle === undefined ? null : toSummary(bundle.fixture, 'gameday');
    }

    // No pin yet — this round has not actually been generated (or generation failed). Falls back to
    // "what would a new round use right now" purely for a best-effort banner; never invented for a
    // round that already has a real, pinned answer.
    if (entry.fixtureOrder.length === 0) return null;
    const poolIndex = roundIndex % entry.fixtureOrder.length;
    const fallbackFixtureId = entry.fixtureOrder[poolIndex] ?? null;
    if (fallbackFixtureId === null) return null;

    const bundle = entry.bundle.fixtures.find((candidate) => candidate.fixture.id === fallbackFixtureId);
    return bundle === undefined ? null : toSummary(bundle.fixture, 'gameday');
  }

  if (meta.fixtureId !== null) {
    const bundle = getCachedBundle(roomId);
    return bundle === null ? null : toSummary(bundle.fixture, 'single');
  }

  return null;
};
