/**
 * Test-only copy of the recorded PSG 6-1 Slovan Bratislava timeline (ESPN fixture 401915445,
 * UCL 2026-09-09) and its confirmed lineups, taken verbatim from
 * `packages/football-data/data/timelines/401915445.json` and `data/competitions/champions-league.json`.
 *
 * game-core may only `import type` from @fdg/football-data, so the recorded data is copied here
 * rather than loaded through the data package's runtime. Excluded from the build (`*.test-utils.ts`).
 * Generated by a one-off script; do not hand-edit — regenerate from the source files instead.
 */

import type { Fixture, FixtureLineups, MatchEvent } from '@fdg/football-data';

export const PSG_SLOVAN_FIXTURE = {
  "id": "401915445",
  "competitionId": "champions-league",
  "season": "2026/27",
  "kickoff": "2026-09-09T19:00:00.000Z",
  "status": "FINISHED",
  "minute": null,
  "homeTeam": {
    "id": "160",
    "name": "Paris Saint-Germain",
    "shortName": "PSG",
    "crestUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
    "country": null
  },
  "awayTeam": {
    "id": "521",
    "name": "Slovan Bratislava",
    "shortName": "SLB",
    "crestUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
    "country": null
  },
  "score": {
    "home": 6,
    "away": 1
  },
  "halfTimeScore": {
    "home": 3,
    "away": 0
  },
  "venue": "Parc des Princes",
  "round": null
} as unknown as Fixture;

export const PSG_SLOVAN_LINEUPS = {
  "fixtureId": "401915445",
  "home": {
    "teamId": "160",
    "formation": "4-3-3",
    "coachName": null,
    "startingXI": [
      {
        "playerId": "248699",
        "name": "Matvei Safonov",
        "shirtNumber": 39,
        "position": "GK",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "240233",
        "name": "Achraf Hakimi",
        "shirtNumber": 2,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "290591",
        "name": "Nuno Mendes",
        "shirtNumber": 25,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "288897",
        "name": "Vitinha",
        "shirtNumber": 17,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "304503",
        "name": "Illia Zabarnyi",
        "shirtNumber": 6,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "287005",
        "name": "Willian Pacho",
        "shirtNumber": 51,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "403578",
        "name": "Dro Fernández",
        "shirtNumber": 27,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "214596",
        "name": "Fabián Ruiz",
        "shirtNumber": 8,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "229744",
        "name": "Ousmane Dembélé",
        "shirtNumber": 10,
        "position": "FW",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "329690",
        "name": "Maghnes Akliouche",
        "shirtNumber": 11,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "265869",
        "name": "Ferran Torres",
        "shirtNumber": 9,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": true
      }
    ],
    "substitutes": [
      {
        "playerId": "160115",
        "name": "Lucas Digne",
        "shirtNumber": 12,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "336388",
        "name": "Désiré Doué",
        "shirtNumber": 14,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "288925",
        "name": "Lucas Chevalier",
        "shirtNumber": 30,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "274745",
        "name": "Khvicha Kvaratskhelia",
        "shirtNumber": 7,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "159047",
        "name": "Marquinhos",
        "shirtNumber": 5,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "355061",
        "name": "João Neves",
        "shirtNumber": 87,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "196200",
        "name": "Lucas Hernández",
        "shirtNumber": 21,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "403419",
        "name": "Quentin Ndjantou",
        "shirtNumber": 47,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "379088",
        "name": "Senny Mayulu",
        "shirtNumber": 24,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "345581",
        "name": "Warren Zaïre-Emery",
        "shirtNumber": 33,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "316128",
        "name": "Lucas Beraldo",
        "shirtNumber": 4,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "353363",
        "name": "Mika Godts",
        "shirtNumber": 22,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      }
    ]
  },
  "away": {
    "teamId": "521",
    "formation": "4-1-4-1",
    "coachName": null,
    "startingXI": [
      {
        "playerId": "275486",
        "name": "Dominik Takac",
        "shirtNumber": 71,
        "position": "GK",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "260346",
        "name": "César Blackman",
        "shirtNumber": 28,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "340556",
        "name": "Sandro Cruz",
        "shirtNumber": 57,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "307484",
        "name": "Peter Pokorny",
        "shirtNumber": 3,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "238958",
        "name": "Kenan Bajric",
        "shirtNumber": 12,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "260751",
        "name": "Svetozar Markovic",
        "shirtNumber": 15,
        "position": "DF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "235045",
        "name": "Tigran Barseghyan",
        "shirtNumber": 11,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "176145",
        "name": "Cristian Martínez",
        "shirtNumber": 70,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "189717",
        "name": "Andraz Sporar",
        "shirtNumber": 99,
        "position": "FW",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "386509",
        "name": "Rahim Ibrahim",
        "shirtNumber": 5,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      },
      {
        "playerId": "310419",
        "name": "Suleiman Camara",
        "shirtNumber": 21,
        "position": "MF",
        "gridPosition": null,
        "isStarter": true
      }
    ],
    "substitutes": [
      {
        "playerId": "401989",
        "name": "Alasana Yirajang",
        "shirtNumber": 14,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "275601",
        "name": "Alen Mustafic",
        "shirtNumber": 20,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "356479",
        "name": "Sahmkou Camara",
        "shirtNumber": 49,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "340723",
        "name": "Artur Gajdos",
        "shirtNumber": 8,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "286533",
        "name": "Daiki Matsuoka",
        "shirtNumber": 88,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "174526",
        "name": "Kevin Wimmer",
        "shirtNumber": 6,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "140813",
        "name": "Aleksander Popovic",
        "shirtNumber": 1,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "275396",
        "name": "Danylo Ignatenko",
        "shirtNumber": 77,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "321179",
        "name": "Samuel Kozlovsky",
        "shirtNumber": 2,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "395638",
        "name": "Alexej Maros",
        "shirtNumber": 29,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "360153",
        "name": "Nino Marcelli",
        "shirtNumber": 10,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      },
      {
        "playerId": "335914",
        "name": "Roman Cerepkai",
        "shirtNumber": 13,
        "position": "UNKNOWN",
        "gridPosition": null,
        "isStarter": false
      }
    ]
  },
  "confirmed": true
} as unknown as FixtureLineups;

/** The full recorded event list, kick-off to full time, in provider order. */
export const PSG_SLOVAN_EVENTS = [
  {"id": "espn:52130251", "fixtureId": "401915445", "type": "KICK_OFF", "minute": 0, "extraMinute": null, "teamId": null, "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": null},
  {"id": "espn:52130533", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 3, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "240233", "detail": "Attempt blocked. Ousmane Dembélé (Paris Saint Germain) left footed shot from the centre of the box is blocked. Assisted by Achraf Hakimi."},
  {"id": "espn:52130459", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 3, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": "229744", "detail": "Attempt saved. Dro Fernández (Paris Saint Germain) right footed shot from the centre of the box is saved in the centre of the goal by Dominik Takác (Slovan Bratislava). Assisted by Ousmane Dembélé."},
  {"id": "espn:52130461", "fixtureId": "401915445", "type": "CORNER", "minute": 3, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Dominik Takác."},
  {"id": "espn:52131006", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 7, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "403578", "detail": "Attempt blocked. Ousmane Dembélé (Paris Saint Germain) left footed shot from the right side of the box is blocked. Assisted by Dro Fernández."},
  {"id": "espn:52131144", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 7, "extraMinute": null, "teamId": "160", "playerId": "214596", "playerName": "Fabián Ruiz", "relatedPlayerId": "403578", "detail": "Attempt blocked. Fabián Ruiz (Paris Saint Germain) right footed shot from the centre of the box is blocked. Assisted by Dro Fernández with a cross."},
  {"id": "espn:52131146", "fixtureId": "401915445", "type": "FOUL", "minute": 7, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": "340556", "detail": "Foul by Dro Fernández (Paris Saint Germain)."},
  {"id": "espn:52131261", "fixtureId": "401915445", "type": "FOUL", "minute": 9, "extraMinute": null, "teamId": "160", "playerId": "329690", "playerName": "Maghnes Akliouche", "relatedPlayerId": "310419", "detail": "Foul by Maghnes Akliouche (Paris Saint Germain)."},
  {"id": "espn:52131642", "fixtureId": "401915445", "type": "FOUL", "minute": 12, "extraMinute": null, "teamId": "160", "playerId": "214596", "playerName": "Fabián Ruiz", "relatedPlayerId": "310419", "detail": "Foul by Fabián Ruiz (Paris Saint Germain)."},
  {"id": "espn:52132203", "fixtureId": "401915445", "type": "CORNER", "minute": 16, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Rahim Ibrahim."},
  {"id": "espn:52132212", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 17, "extraMinute": null, "teamId": "160", "playerId": "290591", "playerName": "Nuno Mendes", "relatedPlayerId": null, "detail": "Nuno Mendes (Paris Saint Germain) hits the right post with a left footed shot from outside the box following a corner."},
  {"id": "espn:52132213", "fixtureId": "401915445", "type": "GOAL", "minute": 17, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": null, "detail": "Goal! Paris Saint Germain 1, Slovan Bratislava 0. Ousmane Dembélé (Paris Saint Germain) left footed shot from the centre of the box to the bottom right corner following a corner."},
  {"id": "espn:52132344", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 18, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "265869", "detail": "Attempt missed. Ousmane Dembélé (Paris Saint Germain) left footed shot from the left side of the box is close, but misses to the right. Assisted by Ferran Torres with a through ball following a fast break."},
  {"id": "espn:52132502", "fixtureId": "401915445", "type": "FOUL", "minute": 19, "extraMinute": null, "teamId": "521", "playerId": "340556", "playerName": "Sandro Cruz", "relatedPlayerId": "403578", "detail": "Dro Fernández (Paris Saint Germain) wins a free kick in the defensive half."},
  {"id": "espn:52132540", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 20, "extraMinute": null, "teamId": "160", "playerId": "329690", "playerName": "Maghnes Akliouche", "relatedPlayerId": "240233", "detail": "Attempt missed. Maghnes Akliouche (Paris Saint Germain) left footed shot from outside the box misses to the left. Assisted by Achraf Hakimi."},
  {"id": "espn:52132744", "fixtureId": "401915445", "type": "KICK_OFF", "minute": 21, "extraMinute": null, "teamId": "521", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Delay in match because of an injury Kenan Bajric (Slovan Bratislava)."},
  {"id": "espn:52132745", "fixtureId": "401915445", "type": "KICK_OFF", "minute": 21, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": null},
  {"id": "espn:52132754", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 22, "extraMinute": null, "teamId": "521", "playerId": "238958", "playerName": "Kenan Bajric", "relatedPlayerId": "356479", "detail": "Substitution, Slovan Bratislava. Sahmkou Camara replaces Kenan Bajric because of an injury."},
  {"id": "espn:52132953", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 23, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": "329690", "detail": "Attempt blocked. Dro Fernández (Paris Saint Germain) right footed shot from the right side of the box is blocked. Assisted by Maghnes Akliouche."},
  {"id": "espn:52132955", "fixtureId": "401915445", "type": "GOAL", "minute": 23, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": null, "detail": "Goal! Paris Saint Germain 2, Slovan Bratislava 0. Ousmane Dembélé (Paris Saint Germain) header from very close range to the bottom left corner."},
  {"id": "espn:52133164", "fixtureId": "401915445", "type": "CORNER", "minute": 25, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Svetozar Markovic."},
  {"id": "espn:52133169", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 25, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "229744", "detail": "Attempt missed. Ferran Torres (Paris Saint Germain) right footed shot from the centre of the box is just a bit too high. Assisted by Ousmane Dembélé with a cross following a corner."},
  {"id": "espn:52133281", "fixtureId": "401915445", "type": "FOUL", "minute": 26, "extraMinute": null, "teamId": "160", "playerId": "304503", "playerName": "Illia Zabarnyi", "relatedPlayerId": "386509", "detail": "Foul by Illia Zabarnyi (Paris Saint Germain)."},
  {"id": "espn:52133408", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 27, "extraMinute": null, "teamId": "160", "playerId": "329690", "playerName": "Maghnes Akliouche", "relatedPlayerId": null, "detail": "Attempt missed. Maghnes Akliouche (Paris Saint Germain) left footed shot from the right side of the box is too high."},
  {"id": "espn:52133422", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 27, "extraMinute": null, "teamId": "521", "playerId": "310419", "playerName": "Suleiman Camara", "relatedPlayerId": "386509", "detail": "Attempt blocked. Suleiman Camara (Slovan Bratislava) right footed shot from the centre of the box is blocked. Assisted by Rahim Ibrahim."},
  {"id": "espn:52133473", "fixtureId": "401915445", "type": "FOUL", "minute": 28, "extraMinute": null, "teamId": "521", "playerId": "176145", "playerName": "Cristian Martínez", "relatedPlayerId": "229744", "detail": "Ousmane Dembélé (Paris Saint Germain) wins a free kick in the attacking half."},
  {"id": "espn:52133553", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 29, "extraMinute": null, "teamId": "160", "playerId": "290591", "playerName": "Nuno Mendes", "relatedPlayerId": null, "detail": "Attempt saved. Nuno Mendes (Paris Saint Germain) left footed shot from outside the box is saved in the centre of the goal by Dominik Takác (Slovan Bratislava)."},
  {"id": "espn:52133643", "fixtureId": "401915445", "type": "FOUL", "minute": 30, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "189717", "detail": "Foul by Ousmane Dembélé (Paris Saint Germain)."},
  {"id": "espn:52133661", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 30, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "240233", "detail": "Attempt missed. Ferran Torres (Paris Saint Germain) right footed shot from outside the box is close, but misses to the right. Assisted by Achraf Hakimi."},
  {"id": "espn:52133829", "fixtureId": "401915445", "type": "GOAL", "minute": 31, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "229744", "detail": "Goal! Paris Saint Germain 3, Slovan Bratislava 0. Ferran Torres (Paris Saint Germain) right footed shot from very close range to the bottom right corner. Assisted by Ousmane Dembélé with a cross."},
  {"id": "espn:52134061", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 33, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "240233", "detail": "Attempt missed. Ousmane Dembélé (Paris Saint Germain) right footed shot from the right side of the box misses to the left. Assisted by Achraf Hakimi."},
  {"id": "espn:52134226", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 34, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "265869", "detail": "Attempt saved. Ousmane Dembélé (Paris Saint Germain) right footed shot from very close range is saved in the centre of the goal by Dominik Takác (Slovan Bratislava). Assisted by Ferran Torres with a headed pass."},
  {"id": "espn:52134379", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 36, "extraMinute": null, "teamId": "160", "playerId": "240233", "playerName": "Achraf Hakimi", "relatedPlayerId": "329690", "detail": "Attempt missed. Achraf Hakimi (Paris Saint Germain) right footed shot from the right side of the box is high and wide to the right. Assisted by Maghnes Akliouche with a through ball."},
  {"id": "espn:52134438", "fixtureId": "401915445", "type": "FOUL", "minute": 37, "extraMinute": null, "teamId": "160", "playerId": "290591", "playerName": "Nuno Mendes", "relatedPlayerId": "235045", "detail": "Foul by Nuno Mendes (Paris Saint Germain)."},
  {"id": "espn:52134570", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 38, "extraMinute": null, "teamId": "521", "playerId": "235045", "playerName": "Tigran Barseghyan", "relatedPlayerId": null, "detail": "Attempt saved. Tigran Barseghyan (Slovan Bratislava) left footed shot from outside the box is saved in the bottom left corner by Matvey Safonov (Paris Saint Germain)."},
  {"id": "espn:52134581", "fixtureId": "401915445", "type": "CORNER", "minute": 39, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Sahmkou Camara."},
  {"id": "espn:52134686", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 40, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "214596", "detail": "Attempt missed. Ousmane Dembélé (Paris Saint Germain) left footed shot from outside the box is close, but misses to the left. Assisted by Fabián Ruiz."},
  {"id": "espn:52135095", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 43, "extraMinute": null, "teamId": "160", "playerId": "240233", "playerName": "Achraf Hakimi", "relatedPlayerId": "229744", "detail": "Attempt saved. Achraf Hakimi (Paris Saint Germain) right footed shot from outside the box is saved in the bottom left corner by Dominik Takác (Slovan Bratislava). Assisted by Ousmane Dembélé."},
  {"id": "espn:52135106", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 44, "extraMinute": null, "teamId": "521", "playerId": "310419", "playerName": "Suleiman Camara", "relatedPlayerId": "176145", "detail": "Attempt blocked. Suleiman Camara (Slovan Bratislava) header from the left side of the six yard box is blocked. Assisted by Cristian Martínez."},
  {"id": "espn:52135207", "fixtureId": "401915445", "type": "OFFSIDE", "minute": 44, "extraMinute": null, "teamId": "160", "playerId": "290591", "playerName": "Nuno Mendes", "relatedPlayerId": null, "detail": "Offside, Paris Saint Germain. Ousmane Dembélé is caught offside."},
  {"id": "espn:52135218", "fixtureId": "401915445", "type": "FOUL", "minute": 45, "extraMinute": null, "teamId": "521", "playerId": "386509", "playerName": "Rahim Ibrahim", "relatedPlayerId": "329690", "detail": "Maghnes Akliouche (Paris Saint Germain) wins a free kick in the defensive half."},
  {"id": "espn:52135379", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 45, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": null, "detail": "Attempt missed. Ousmane Dembélé (Paris Saint Germain) right footed shot from the right side of the box is too high."},
  {"id": "espn:52135403", "fixtureId": "401915445", "type": "FOUL", "minute": 45, "extraMinute": 2, "teamId": "521", "playerId": "356479", "playerName": "Sahmkou Camara", "relatedPlayerId": "265869", "detail": "Ferran Torres (Paris Saint Germain) wins a free kick in the attacking half."},
  {"id": "espn:52135439", "fixtureId": "401915445", "type": "HALF_TIME", "minute": 45, "extraMinute": 2, "teamId": null, "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "First Half ends, Paris Saint Germain 3, Slovan Bratislava 0."},
  {"id": "espn:52136434", "fixtureId": "401915445", "type": "KICK_OFF", "minute": 46, "extraMinute": null, "teamId": null, "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": null},
  {"id": "espn:52136572", "fixtureId": "401915445", "type": "GOAL", "minute": 47, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "329690", "detail": "Goal! Paris Saint Germain 4, Slovan Bratislava 0. Ferran Torres (Paris Saint Germain) right footed shot from outside the box to the bottom right corner. Assisted by Maghnes Akliouche."},
  {"id": "espn:52136821", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 50, "extraMinute": null, "teamId": "160", "playerId": "214596", "playerName": "Fabián Ruiz", "relatedPlayerId": null, "detail": "Attempt missed. Fabián Ruiz (Paris Saint Germain) left footed shot from outside the box is high and wide to the left."},
  {"id": "espn:52137123", "fixtureId": "401915445", "type": "OFFSIDE", "minute": 51, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": null, "detail": "Offside, Paris Saint Germain. Fabián Ruiz is caught offside."},
  {"id": "espn:52137280", "fixtureId": "401915445", "type": "FOUL", "minute": 53, "extraMinute": null, "teamId": "521", "playerId": "260346", "playerName": "César Blackman", "relatedPlayerId": "290591", "detail": "Nuno Mendes (Paris Saint Germain) wins a free kick on the left wing."},
  {"id": "espn:52137401", "fixtureId": "401915445", "type": "YELLOW_CARD", "minute": 53, "extraMinute": null, "teamId": "521", "playerId": "260346", "playerName": "César Blackman", "relatedPlayerId": null, "detail": "César Blackman (Slovan Bratislava) is shown the yellow card for a bad foul."},
  {"id": "espn:52137411", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 54, "extraMinute": null, "teamId": "521", "playerId": "310419", "playerName": "Suleiman Camara", "relatedPlayerId": "189717", "detail": "Attempt missed. Suleiman Camara (Slovan Bratislava) right footed shot from outside the box is too high. Assisted by Andraz Sporar following a fast break."},
  {"id": "espn:52137583", "fixtureId": "401915445", "type": "OFFSIDE", "minute": 55, "extraMinute": null, "teamId": "160", "playerId": "329690", "playerName": "Maghnes Akliouche", "relatedPlayerId": null, "detail": "Offside, Paris Saint Germain. Nuno Mendes is caught offside."},
  {"id": "espn:52137735", "fixtureId": "401915445", "type": "CORNER", "minute": 56, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Peter Pokorny."},
  {"id": "espn:52137737", "fixtureId": "401915445", "type": "GOAL", "minute": 57, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "229744", "detail": "Goal! Paris Saint Germain 5, Slovan Bratislava 0. Ferran Torres (Paris Saint Germain) right footed shot from the centre of the box to the bottom right corner. Assisted by Ousmane Dembélé with a cross following a corner."},
  {"id": "espn:52137903", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 58, "extraMinute": null, "teamId": "160", "playerId": "329690", "playerName": "Maghnes Akliouche", "relatedPlayerId": "229744", "detail": "Attempt missed. Maghnes Akliouche (Paris Saint Germain) right footed shot from the centre of the box misses to the left. Assisted by Ousmane Dembélé."},
  {"id": "espn:52137910", "fixtureId": "401915445", "type": "GOAL", "minute": 58, "extraMinute": null, "teamId": "521", "playerId": "310419", "playerName": "Suleiman Camara", "relatedPlayerId": "235045", "detail": "Goal! Paris Saint Germain 5, Slovan Bratislava 1. Suleiman Camara (Slovan Bratislava) right footed shot from the left side of the box to the top right corner. Assisted by Tigran Barseghyan."},
  {"id": "espn:52137999", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 60, "extraMinute": null, "teamId": "521", "playerId": "235045", "playerName": "Tigran Barseghyan", "relatedPlayerId": "360153", "detail": "Substitution, Slovan Bratislava. Nino Marcelli replaces Tigran Barseghyan."},
  {"id": "espn:52138000", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 60, "extraMinute": null, "teamId": "521", "playerId": "386509", "playerName": "Rahim Ibrahim", "relatedPlayerId": "275601", "detail": "Substitution, Slovan Bratislava. Alen Mustafic replaces Rahim Ibrahim."},
  {"id": "espn:52138085", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 61, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": "290591", "detail": "Attempt blocked. Dro Fernández (Paris Saint Germain) left footed shot from the centre of the box is blocked. Assisted by Nuno Mendes."},
  {"id": "espn:52138378", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 62, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": null, "detail": "Attempt blocked. Ousmane Dembélé (Paris Saint Germain) right footed shot from outside the box is blocked."},
  {"id": "espn:52138588", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 64, "extraMinute": null, "teamId": "160", "playerId": "287005", "playerName": "Willian Pacho", "relatedPlayerId": "196200", "detail": "Substitution, Paris Saint Germain. Lucas Hernández replaces Willian Pacho."},
  {"id": "espn:52138759", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 64, "extraMinute": null, "teamId": "160", "playerId": "229744", "playerName": "Ousmane Dembélé", "relatedPlayerId": "353363", "detail": "Substitution, Paris Saint Germain. Mika Godts replaces Ousmane Dembélé."},
  {"id": "espn:52138760", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 64, "extraMinute": null, "teamId": "160", "playerId": "240233", "playerName": "Achraf Hakimi", "relatedPlayerId": "379088", "detail": "Substitution, Paris Saint Germain. Senny Mayulu replaces Achraf Hakimi."},
  {"id": "espn:52138761", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 64, "extraMinute": null, "teamId": "160", "playerId": "290591", "playerName": "Nuno Mendes", "relatedPlayerId": "160115", "detail": "Substitution, Paris Saint Germain. Lucas Digne replaces Nuno Mendes."},
  {"id": "espn:52138793", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 65, "extraMinute": null, "teamId": "160", "playerId": "353363", "playerName": "Mika Godts", "relatedPlayerId": "288897", "detail": "Attempt saved. Mika Godts (Paris Saint Germain) right footed shot from the centre of the box is saved in the bottom left corner by Dominik Takác (Slovan Bratislava). Assisted by Vitinha."},
  {"id": "espn:52138877", "fixtureId": "401915445", "type": "CORNER", "minute": 65, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Dominik Takác."},
  {"id": "espn:52138879", "fixtureId": "401915445", "type": "OFFSIDE", "minute": 66, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": null, "detail": "Offside, Paris Saint Germain. Mika Godts is caught offside."},
  {"id": "espn:52139116", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 68, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "214596", "detail": "Attempt missed. Ferran Torres (Paris Saint Germain) right footed shot from outside the box is high and wide to the right. Assisted by Fabián Ruiz."},
  {"id": "espn:52139358", "fixtureId": "401915445", "type": "FOUL", "minute": 69, "extraMinute": null, "teamId": "160", "playerId": "160115", "playerName": "Lucas Digne", "relatedPlayerId": "310419", "detail": "Foul by Lucas Digne (Paris Saint Germain)."},
  {"id": "espn:52139731", "fixtureId": "401915445", "type": "FOUL", "minute": 73, "extraMinute": null, "teamId": "521", "playerId": "340556", "playerName": "Sandro Cruz", "relatedPlayerId": "329690", "detail": "Maghnes Akliouche (Paris Saint Germain) wins a free kick on the right wing."},
  {"id": "espn:52139861", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 73, "extraMinute": null, "teamId": "160", "playerId": "265869", "playerName": "Ferran Torres", "relatedPlayerId": "316128", "detail": "Substitution, Paris Saint Germain. Beraldo replaces Ferran Torres."},
  {"id": "espn:52140114", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 76, "extraMinute": null, "teamId": "160", "playerId": "214596", "playerName": "Fabián Ruiz", "relatedPlayerId": null, "detail": "Attempt missed. Fabián Ruiz (Paris Saint Germain) left footed shot from outside the box is just a bit too high."},
  {"id": "espn:52140241", "fixtureId": "401915445", "type": "OFFSIDE", "minute": 76, "extraMinute": null, "teamId": "521", "playerId": "360153", "playerName": "Nino Marcelli", "relatedPlayerId": null, "detail": "Offside, Slovan Bratislava. Andraz Sporar is caught offside."},
  {"id": "espn:52140438", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 78, "extraMinute": null, "teamId": "160", "playerId": "379088", "playerName": "Senny Mayulu", "relatedPlayerId": "353363", "detail": "Attempt saved. Senny Mayulu (Paris Saint Germain) left footed shot from the left side of the box is saved in the top centre of the goal by Dominik Takác (Slovan Bratislava). Assisted by Mika Godts."},
  {"id": "espn:52140457", "fixtureId": "401915445", "type": "FOUL", "minute": 79, "extraMinute": null, "teamId": "160", "playerId": "160115", "playerName": "Lucas Digne", "relatedPlayerId": "275601", "detail": "Foul by Lucas Digne (Paris Saint Germain)."},
  {"id": "espn:52140516", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 80, "extraMinute": null, "teamId": "521", "playerId": "189717", "playerName": "Andraz Sporar", "relatedPlayerId": "395638", "detail": "Substitution, Slovan Bratislava. Alexej Maros replaces Andraz Sporar."},
  {"id": "espn:52140517", "fixtureId": "401915445", "type": "SUBSTITUTION", "minute": 80, "extraMinute": null, "teamId": "521", "playerId": "176145", "playerName": "Cristian Martínez", "relatedPlayerId": "340723", "detail": "Substitution, Slovan Bratislava. Artur Gajdos replaces Cristian Martínez."},
  {"id": "espn:52140636", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 80, "extraMinute": null, "teamId": "160", "playerId": "379088", "playerName": "Senny Mayulu", "relatedPlayerId": "288897", "detail": "Attempt saved. Senny Mayulu (Paris Saint Germain) left footed shot from outside the box is saved in the centre of the goal by Dominik Takác (Slovan Bratislava). Assisted by Vitinha."},
  {"id": "espn:52140883", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 83, "extraMinute": null, "teamId": "521", "playerId": "310419", "playerName": "Suleiman Camara", "relatedPlayerId": null, "detail": "Attempt saved. Suleiman Camara (Slovan Bratislava) right footed shot from outside the box is saved in the top right corner by Matvey Safonov (Paris Saint Germain)."},
  {"id": "espn:52141164", "fixtureId": "401915445", "type": "CORNER", "minute": 86, "extraMinute": null, "teamId": "521", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Slovan Bratislava. Conceded by Lucas Digne."},
  {"id": "espn:52141220", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 86, "extraMinute": null, "teamId": "521", "playerId": "275601", "playerName": "Alen Mustafic", "relatedPlayerId": "340723", "detail": "Attempt blocked. Alen Mustafic (Slovan Bratislava) header from the centre of the box is blocked. Assisted by Artur Gajdos with a cross."},
  {"id": "espn:52141222", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 86, "extraMinute": null, "teamId": "521", "playerId": "275601", "playerName": "Alen Mustafic", "relatedPlayerId": null, "detail": "Attempt saved. Alen Mustafic (Slovan Bratislava) left footed shot from the centre of the box is saved in the centre of the goal by Matvey Safonov (Paris Saint Germain)."},
  {"id": "espn:52141234", "fixtureId": "401915445", "type": "SHOT_ON_TARGET", "minute": 87, "extraMinute": null, "teamId": "160", "playerId": "403578", "playerName": "Dro Fernández", "relatedPlayerId": "329690", "detail": "Attempt saved. Dro Fernández (Paris Saint Germain) right footed shot from the centre of the box is saved in the top right corner by Dominik Takác (Slovan Bratislava). Assisted by Maghnes Akliouche."},
  {"id": "espn:52141236", "fixtureId": "401915445", "type": "CORNER", "minute": 87, "extraMinute": null, "teamId": "160", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Paris Saint Germain. Conceded by Dominik Takác."},
  {"id": "espn:52141318", "fixtureId": "401915445", "type": "GOAL", "minute": 87, "extraMinute": null, "teamId": "160", "playerId": "214596", "playerName": "Fabián Ruiz", "relatedPlayerId": null, "detail": "Goal! Paris Saint Germain 6, Slovan Bratislava 1. Fabián Ruiz (Paris Saint Germain) left footed shot from the centre of the box to the bottom left corner following a corner."},
  {"id": "espn:52141598", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 90, "extraMinute": null, "teamId": "160", "playerId": "353363", "playerName": "Mika Godts", "relatedPlayerId": "379088", "detail": "Attempt missed. Mika Godts (Paris Saint Germain) left footed shot from the centre of the box is close, but misses to the right. Assisted by Senny Mayulu."},
  {"id": "espn:52141605", "fixtureId": "401915445", "type": "SHOT_OFF_TARGET", "minute": 90, "extraMinute": 1, "teamId": "521", "playerId": "360153", "playerName": "Nino Marcelli", "relatedPlayerId": "260346", "detail": "Attempt missed. Nino Marcelli (Slovan Bratislava) right footed shot from outside the box misses to the right. Assisted by César Blackman."},
  {"id": "espn:52141659", "fixtureId": "401915445", "type": "CORNER", "minute": 90, "extraMinute": 2, "teamId": "521", "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": "Corner, Slovan Bratislava. Conceded by Illia Zabarnyi."},
  {"id": "espn:52141823", "fixtureId": "401915445", "type": "FULL_TIME", "minute": 90, "extraMinute": 2, "teamId": null, "playerId": null, "playerName": null, "relatedPlayerId": null, "detail": null},
] as unknown as readonly MatchEvent[];
